import { useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity } from "react-native";
import { router, Stack, useLocalSearchParams } from "expo-router";
import { registrarMuerte } from "../../src/services/animalService";

export default function Muerte(){
  const params=useLocalSearchParams<{animalId:string|string[];enfermedadId?:string;causa?:string;numero?:string;nombre?:string}>();
  const animalId=Array.isArray(params.animalId)?params.animalId[0]:params.animalId;const [causa,setCausa]=useState(params.causa||"");const [guardando,setGuardando]=useState(false);
  function confirmar(){if(!causa.trim())return Alert.alert("Falta la causa","Escribe la causa de muerte.");Alert.alert("Confirmar muerte","El animal saldrá del inventario activo y conservará todo su historial.",[{text:"Cancelar",style:"cancel"},{text:"Confirmar",style:"destructive",onPress:async()=>{if(!animalId||guardando)return;setGuardando(true);try{await registrarMuerte(animalId,params.enfermedadId,causa.trim());Alert.alert("Registro guardado","El animal pasó a la lista de fallecidos.",[{text:"Listo",onPress:()=>router.dismissAll()}]);}catch{Alert.alert("Error","No fue posible registrar la muerte.");setGuardando(false);}}}]);}
  return <ScrollView style={styles.container} contentContainerStyle={styles.contenido} keyboardShouldPersistTaps="handled"><Stack.Screen options={{title:"Registrar muerte"}}/><Text style={styles.animal}>{params.numero?`Vaca ${params.numero}${params.nombre?` · ${params.nombre}`:""}`:params.nombre||"Animal"}</Text><Text style={styles.titulo}>Muerte</Text>{params.enfermedadId?<Text style={styles.vinculo}>Vinculada a una enfermedad registrada</Text>:null}<Text style={styles.label}>Causa</Text><TextInput style={styles.input} multiline placeholder="Obligatorio" value={causa} onChangeText={setCausa}/><TouchableOpacity style={[styles.boton,guardando&&styles.disabled]} disabled={guardando} onPress={confirmar}><Text style={styles.botonTexto}>{guardando?"Guardando…":"Registrar muerte"}</Text></TouchableOpacity></ScrollView>;
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:"#fff"},contenido:{padding:20,paddingBottom:40},animal:{color:"#2e7d32",fontSize:16,fontWeight:"700"},titulo:{fontSize:28,fontWeight:"700",marginTop:6},vinculo:{color:"#555",marginTop:8},label:{fontSize:16,fontWeight:"700",marginTop:24,marginBottom:8},input:{minHeight:120,borderWidth:1,borderColor:"#ccc",borderRadius:12,padding:14,fontSize:18,textAlignVertical:"top"},boton:{minHeight:60,backgroundColor:"#b3261e",borderRadius:12,alignItems:"center",justifyContent:"center",marginTop:28},botonTexto:{color:"#fff",fontSize:18,fontWeight:"700"},disabled:{opacity:.5}});
