import { useCallback, useState } from "react";
import { Alert, FlatList, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { router, Stack, useFocusEffect, useLocalSearchParams } from "expo-router";
import { listarEvoluciones, obtenerEvento, registrarEvolucion, registrarRecuperacion } from "../../../src/services/animalService";

type Evento={id:string;animal_id:string;diagnostico:string|null;tratamiento:string|null;nota:string|null;fecha:string;resuelto_en:string|null};
export default function DetalleEnfermedad(){
  const {id}=useLocalSearchParams<{id:string}>(); const [enfermedad,setEnfermedad]=useState<Evento|null>(null); const [evoluciones,setEvoluciones]=useState<Evento[]>([]); const [nota,setNota]=useState(""); const [guardando,setGuardando]=useState(false);
  const cargar=useCallback(async()=>{if(!id)return;const [evento,lista]=await Promise.all([obtenerEvento(id),listarEvoluciones(id)]);setEnfermedad(evento as Evento|null);setEvoluciones(lista as Evento[]);},[id]);
  useFocusEffect(useCallback(()=>{cargar();},[cargar]));
  async function agregar(){if(!nota.trim()||!enfermedad||guardando)return;setGuardando(true);try{await registrarEvolucion({animalId:enfermedad.animal_id,enfermedadId:id,nota:nota.trim()});setNota("");await cargar();}catch{Alert.alert("Error","No fue posible guardar la evolución.");}finally{setGuardando(false);}}
  function confirmarRecuperacion(){if(!enfermedad||enfermedad.resuelto_en)return;Alert.alert("Marcar como recuperada","El episodio quedará cerrado y conservará todo su seguimiento.",[{text:"Cancelar",style:"cancel"},{text:"Confirmar",onPress:async()=>{try{await registrarRecuperacion({animalId:enfermedad.animal_id,enfermedadId:id,nota:nota.trim()||null});setNota("");await cargar();Alert.alert("Recuperación registrada","El episodio quedó cerrado.");}catch{Alert.alert("Error","No fue posible registrar la recuperación.");}}}]);}
  function confirmarMuerte(){if(!enfermedad)return;router.push({pathname:"/evento/muerte",params:{animalId:enfermedad.animal_id,enfermedadId:id,causa:enfermedad.diagnostico||""}});}
  if(!enfermedad)return <View style={styles.centrado}><Text>Cargando…</Text></View>;
  const resuelta=Boolean(enfermedad.resuelto_en);
  return <View style={styles.container}><Stack.Screen options={{title:"Evolución de enfermedad"}}/><FlatList data={evoluciones} keyExtractor={(x)=>x.id} contentContainerStyle={styles.contenido} ListHeaderComponent={<View>{resuelta?<View style={styles.estado}><Text style={styles.estadoTexto}>Recuperada · {new Date(enfermedad.resuelto_en!).toLocaleDateString()}</Text></View>:null}<Text style={styles.label}>Diagnóstico</Text><Text style={styles.diagnostico}>{enfermedad.diagnostico}</Text>{enfermedad.tratamiento?<><Text style={styles.label}>Tratamiento</Text><Text style={styles.diagnostico}>{enfermedad.tratamiento}</Text></>:null}{enfermedad.nota?<Text style={styles.inicial}>Evolución inicial: {enfermedad.nota}</Text>:null}{!resuelta?<><Text style={styles.label}>Nueva evolución</Text><TextInput style={styles.input} multiline placeholder="Describe cómo sigue el animal" value={nota} onChangeText={setNota}/><TouchableOpacity style={styles.guardar} onPress={agregar}><Text style={styles.guardarTexto}>{guardando?"Guardando…":"Agregar evolución"}</Text></TouchableOpacity><TouchableOpacity style={styles.recuperada} onPress={confirmarRecuperacion}><Text style={styles.recuperadaTexto}>Marcar como recuperada</Text></TouchableOpacity></>:null}<Text style={styles.label}>Evoluciones</Text></View>} renderItem={({item})=><View style={styles.evolucion}><Text>{item.nota}</Text><Text style={styles.fecha}>{new Date(item.fecha).toLocaleString()}</Text></View>} ListEmptyComponent={<Text style={styles.vacio}>Todavía no hay evoluciones posteriores.</Text>} ListFooterComponent={!resuelta?<TouchableOpacity style={styles.muerte} onPress={confirmarMuerte}><Text style={styles.muerteTexto}>El animal murió por esta enfermedad</Text></TouchableOpacity>:null}/></View>;
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:"#fff"},centrado:{flex:1,alignItems:"center",justifyContent:"center"},contenido:{padding:20,paddingBottom:50},estado:{backgroundColor:"#e5f4e6",borderRadius:10,padding:12},estadoTexto:{color:"#2e7d32",fontWeight:"700",textAlign:"center"},label:{fontSize:18,fontWeight:"700",marginTop:20,marginBottom:10},diagnostico:{fontSize:20},inicial:{color:"#555",marginTop:12},input:{minHeight:110,borderWidth:1,borderColor:"#ccc",borderRadius:12,padding:14,fontSize:17,textAlignVertical:"top"},guardar:{minHeight:54,backgroundColor:"#2e7d32",borderRadius:12,alignItems:"center",justifyContent:"center",marginTop:10},guardarTexto:{color:"#fff",fontWeight:"700",fontSize:16},recuperada:{minHeight:54,borderWidth:1,borderColor:"#2e7d32",borderRadius:12,alignItems:"center",justifyContent:"center",marginTop:10},recuperadaTexto:{color:"#2e7d32",fontWeight:"700"},evolucion:{borderWidth:1,borderColor:"#e1e1e1",borderRadius:12,padding:14,marginBottom:8},fecha:{color:"#888",fontSize:12,marginTop:6},vacio:{color:"#888",textAlign:"center",marginVertical:15},muerte:{minHeight:54,borderWidth:1,borderColor:"#b3261e",borderRadius:12,alignItems:"center",justifyContent:"center",marginTop:30},muerteTexto:{color:"#b3261e",fontWeight:"700"}});
